### ISSUE TITLE
Curseforge release

### ISSUE THREAD

**Issue by dawsontech30000** [tth05/morerefinedstorage#38]
https://support.curseforge.com/en/support/home
https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods
https://docs.google.com/spreadsheets/d/176Wv-PZUo9hFxy6oC6N8tWdquBLPRtSuLbNK-r0_byM/edit#gid=0

**Comment by Pelotrio** [comment]
The plan is actually to publish it on curseforge. I've been thinking about it for a while, and once a few final changes are made, like fixing #31 , it will be released on curseforge as well. Expect it at the end of the year or the beginning of next year.

**Comment by dawsontech30000** [comment]
well need to know in works of making my pack and your copy rs is a lot better than CF one

**Comment by dawsontech30000** [comment]
good to know atm is rough time when could get this done supply everything you need in first post. do have discord see dev updates is only way contacting you ?

**Comment by Pelotrio** [comment]
I don't completely understand what you are saying but as I said expect it at the end of the year. Also yes I have a discord.

**Comment by lokep001** [comment]
> The plan is actually to publish it on curseforge. I've been thinking about it for a while, and once a few final changes are made, like fixing #31 , it will be released on curseforge as well. Expect it at the end of the year or the beginning of next year.

Is fixing #26 a goal as well? I think if that was to be fixed before release on curseforge, this fork would be perfect.

**Comment by tth05** [comment]
> > The plan is actually to publish it on curseforge. I've been thinking about it for a while, and once a few final changes are made, like fixing #31 , it will be released on curseforge as well. Expect it at the end of the year or the beginning of next year.
> 
> Is fixing #26 a goal as well? I think if that was to be fixed before release on curseforge, this fork would be perfect.

Most likely not for now. As you can see by the comment [here](https://github.com/tth05/morerefinedstorage/issues/26#issuecomment-842377475) it'd be quite a bit of work and probably a mess to implement. I should've thought about it sooner when making the new engine but tbh I didn't think it would come this far.
*Another engine re-write incoming? :)*

**Comment by Pelotrio** [comment]
> Is fixing #26 a goal as well? I think if that was to be fixed before release on curseforge, this fork would be perfect.

It's not really a priority at the moment especially not before the release but will maybe implemented in the future. Shouldn't be a big problem for most packs with good unification unless you need something like logs. I mean how it would work is described there pretty well so if someone would implement that it would of course be added.

**Comment by dawsontech30000** [comment]
is possble to get link to discord so I can keep eye on updates you bring out not normally active on github

**Comment by embeddedt** [comment]
In all honesty, I'm not sure that there's any urgency to release this fork on CurseForge for anyone trying to make a new modpack.

I have looked through the 1.12 kitchen sink I've been working on, with an emphasis on weak hardware having a playable experience, and I already have a lot of custom JARs due to the fact that many mods simply aren't supported anymore and won't be updated on CurseForge even if a community member offered a fix to an issue.

* PrototypeTrousers' [fork](https://github.com/PrototypeTrousers/Applied-Energistics-2) of AE2 which is not on CurseForge.
* The last beta of Compact Machines which was never released on CurseForge.
* [My fork](https://github.com/embeddedt/MUP) of the Eigencraft Unofficial Patch mod that makes it work with Mixin 0.8. Admittedly, this is mostly a vanilla bugfixing mod, but those are necessary for a decent experience after playing newer versions of vanilla.
* [My fork](https://github.com/embeddedt/RSInfiniteWireless) of RSInfiniteWireless that makes it work with More Refined Storage.
* My private fork of VanillaFix that adds a couple more bugfixes. Notably, it rewrites the portal searching logic to use a system designed in a similar vein to the POI system in vanilla, where the portal block positions in a chunk are stored so it doesn't need to scan the entire chunk. This greatly reduces portal lag to the point that transitions became instant in creative mode on a 4th gen i3. I also fixed [MC-31681](https://bugs.mojang.com/browse/MC-31681) which was annoying after playing 1.16.
* My fork of Sledgehammer, which has some more bugfixes that I didn't contribute upstream due to lack of testing. The most important fix there was [MC-88176](https://bugs.mojang.com/browse/MC-88176) which made the Ender Dragon fight very annoying, since the dragon would disappear off the screen while a player stood in the exit portal.

Sorry, that list got a little long, but maybe it'd be interesting for someone.

In general I don't think it's viable to provide support for a 1.12 CurseForge modpack without hacks like ModDirector, as there are going to be bugs. I still have more mods I'd like to get around to patching, e.g. the bug with Extra Utilities where it voids item stacks being added to generators. No time, however. :laughing:

**Comment by lokep001** [comment]
I thought that was interesting! How do you know about so many forks? I only know about this one and prototrousers AE2 fork. Is there like a spreadsheet or something? I don’t like playing 1.16 packs right now because I feel it’s missing a lot of tech, so using these forks adds a breath of fresh air

**Comment by embeddedt** [comment]
Honestly, a lot of them are forks I made myself. There are very few modders who are even willing to discuss 1.12 at this point (and I wouldn't consider myself a modder, I'm just a developer who figured out enough about Minecraft & Forge to patch old mods).

I would also be on 1.16 if it weren't for the lack of tech mods and the very poor performance compared to 1.12.

**Comment by embeddedt** [comment]
You can also hunt around for actively maintained 1.12 modpacks like Divine Journey 2 and Enigmatica 2 Expert Extended; some of them use forks of mods now.

**Comment by Pelotrio** [comment]
> is possble to get link to discord so I can keep eye on updates you bring out not normally active on github

The server was private until now, but we made some changes and anyone who wants can join now. The link is:  https://discord.gg/jNVXP3Vc. Please note that this server is not only about morerefinedstorage but about all our mods.

**Comment by Pelotrio** [comment]
@embeddedt Thanks for your input, but we have been planning to release the mod on Curseforge for a long time. This project, like all of our other mods, was created during our playthrough of All the Mod 3 after we found a lot of inefficiencies. I'm also the maintainer of the modpack, so the plan is to add it in the next update. We also wanted to release our other mods on curse, so it fits quite well.

**Comment by embeddedt** [comment]
@Pelotrio Oh, no problem! I'd be happy to see the mod on CurseForge - it would probably help with visibility as well. Just wanted to point out the issue I've been noting with 1.12 and CurseForge for the last few months. I hope my comment didn't come across in a negative way.

**Comment by Pelotrio** [comment]
> @Pelotrio Oh, no problem! I'd be happy to see the mod on CurseForge - it would probably help with visibility as well. Just wanted to point out the issue I've been noting with 1.12 and CurseForge for the last few months. I hope my comment didn't come across in a negative way.

No, it definitely didn't come across in a negative way, I definitely agree that it's hard to make a 1.12 modpack right now and I've experienced that myself. We ourselves have modified a lot of mods to counter performance issues and have even developed tools to block certain mods. We submitted pull requests for some of them, but many were simply ignored. When I updated ATM 3, I had to ask several mod authors (Plustic and EnderIO) for new versions to fix bugs and compatibility. We also had the idea to just make a core mod that injects mods into mods so we only have to put that on Curse, but unfortunately that's not possible before 1.14. due to how mixins work.

**Comment by Pelotrio** [comment]
As a small update on that, it's still scheduled for release, but we clearly underestimated the time it would take to finish some other things. I think this will happen in the next two months, but I can't guarantee it. I apologize for the delay and that my first estimate was very wrong.

**Comment by lokep001** [comment]
> As a small update on that, it's still scheduled for release, but we clearly underestimated the time it would take to finish some other things. I think this will happen in the next two months, but I can't guarantee it. I apologize for the delay and that my first estimate was very wrong.

Hi Pelotrio, how is progress going? I think this would be a very very good addition to E2E extended personally, but it cant be done until its released on curseforge. 

Thanks for the awesome work on this fork though! :D

**Comment by Pelotrio** [comment]
At this point, I've put in almost all the changes I wanted, but I haven't gotten around to releasing it yet. This project is actually part of a larger project we're working on, but we're having a bit of a down period there. The only thing keeping me from doing it right now is writing a proper description for the Curseforge site. I plan to get that done this week and then I might post it. Sorry again for the long delay

**Comment by lokep001** [comment]
> At this point, I've put in almost all the changes I wanted, but I haven't gotten around to releasing it yet. This project is actually part of a larger project we're working on, but we're having a bit of a down period there. The only thing keeping me from doing it right now is writing a proper description for the Curseforge site. I plan to get that done this week and then I might post it. Sorry again for the long delay

Hype? 👀

**Comment by Pelotrio** [comment]
@dawsontech30000 @lokep001 @embeddedt 
We finally released on both Curseforge and Modrinth 💯 🎉  🚀. The logo is experimental and we haven't released our fork of Reborn Storage yet so this will remain on Github for the time being.  

Links to both projects:

https://www.curseforge.com/minecraft/mc-mods/morerefinedstorage
https://modrinth.com/mod/morerefinedstorage

**Comment by Pelotrio** [comment]
Modrinth is already approved and we are waiting for Curseforge atm.

**Comment by lokep001** [comment]
Great! Hopefully word gets out and people use this in modpacks now!

Expect some complaints though on curseforge comments ;)

**Comment by Pelotrio** [comment]
Definitely looking forward to it (not the cf comments tho lol)

**Comment by lokep001** [comment]
Sorry I've had some thinking about this. May I suggest something? Maybe change the name to Refined Storage Unofficial Extended Life or something similar. It's a direct copy of PAE2's name on curseforge but it could really set the mod out (people download because of titles and they may get confused with the other More Refined Storage and it would be a shame if they missed this out and downloaded the regular one.) PAE2 changed it's name because Prototrouser AE2 doesn't really tell you what the mod is.

That's just my two cents on the topic though.

**Comment by Pelotrio** [comment]
> Sorry I've had some thinking about this. May I suggest something? Maybe change the name to Refined Storage Unofficial Extended Life or something similar. It's a direct copy of PAE2's name on curseforge but it could really set the mod out (people download because of titles and they may get confused with the other More Refined Storage and it would be a shame if they missed this out and downloaded the regular one.) PAE2 changed it's name because Prototrouser AE2 doesn't really tell you what the mod is.
> 
> That's just my two cents on the topic though.

I already thought about something like this and also suggested the idea to @tth05  before publishing, especially because there is already a mod with almost the same name. He wanted to keep that name and its ultimately his call but I'll ask him again if he wants to change it.

**Comment by lokep001** [comment]
Maybe for curseforge change it but keep it the same on github similar to PAE2?

**Comment by Pelotrio** [comment]
That could also work yeah. I'll talk to him about it.
